USE INFOADB;

CREATE TABLE TB_CLIENTE (

ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NM_CLIENTE VARCHAR(200) NOT NULL,
NM_EMAIL VARCHAR(400) NOT NULL,
NR_TELEFONE VARCHAR(200) NOT NULL,
NR_CPF VARCHAR(200) NOT NULL,
NR_CNH INT NOT NULL

);

CREATE TABLE TB_VEICULO (

ID_VEICULO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
TP_VEICULO VARCHAR(100) NOT NULL,
NM_MODELO VARCHAR (400) NOT NULL,
NM_MARCA VARCHAR(400) NOT NULL,
DT_ANO INT NOT NULL,
DS_PLACA VARCHAR(400) NOT NULL

);

CREATE TABLE TB_LOCACAO (

ID_LOCACAO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
ID_CLIENTE INT NOT NULL,
ID_VEICULO INT NOT NULL,
NR_KM_RETIRADA VARCHAR(50) NOT NULL,
DT_LOCACAO DATETIME NOT NULL,
BT_SEGURO BOOL NOT NULL,
DS_OBSERVACOES VARCHAR(800) NOT NULL,
DS_SITUACAO VARCHAR(50) NOT NULL,
NR_KM_ENTREGA INT NOT NULL,
DT_ENTREGA DATETIME NOT NULL,
VL_TOTAL DECIMAL(15,2) NOT NULL,
FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE(ID_CLIENTE),
FOREIGN KEY (ID_VEICULO) REFERENCES TB_VEICULO (ID_VEICULO)

);